package HospiCartJDBC;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import HospiCartInterfaces.IClientManager;
import HospiCartPOJOs.Client;
import HospiCartPOJOs.Role;

/*
 * NOTE: INFO ABOUT ResultSet
 * A table of data representing a database result set, which is usually generated by executing a statement
 * that queries the database.
 * 
 * A ResultSet object maintains a cursor pointing to its current row of data. 
 * Initially the cursor is positioned before the first row. 
 * The next method moves the cursor to the next row, and because it returns false when there are no more 
 * rows in the ResultSet object, it can be used in a while loop to iterate through the result set.
 */

/*
 * NOTE ABOUT THE USAGE OF TRY-WITH-RESOURCES !!!
 * Try-with-resources can only be used if the object implements the Interface AutoCloseable.
 */


public class ClientManager implements IClientManager{
	private ConnectionManagerJDBC manager;

	public ClientManager(ConnectionManagerJDBC m) {
		this.manager = m;
	}
	
	/**
	 * This method responsible for INSERTing a new Client in the database using Prepared Statements.
	 * This method does NOT provide any methods to input from the keyboard. 
	 * It only manages the insertion into the database.
	 * @param c the Client object
	 */
	@Override
	public void insertClient(Client c) {	
		//I call the method that checks if a client was already inserted in the database. If the method returns a false, then I go ahead inserting the client into the database. If it returns true, I don't insert it again.
		if(!isClientInDatabase(c.getEmail())) {
			String sql = "INSERT INTO client (name, surname, phone_number, email, address)" + "VALUES (?,?,?,?,?)"; // 5 "?" corresponding to 5 expressions in the SQL sentence
		
			// 1) Prepare statement and request generated keys
			try (PreparedStatement prep = manager.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)){ // Statement.RETURN_GENERATED_KEYS asks the JDBC driver to capture the new key
				// 2) Bind parameters
				prep.setString(1, c.getName()); // The 1 binds to the first "?". NOTICE THAT IT STARTS FROM 1, NOT 0
				prep.setString(2, c.getSurname());
				prep.setInt(3, c.getPhoneNumber());
				prep.setString(4, c.getEmail());
				prep.setString(5, c.getAddress());
				//prep.setString(6, c.getRole().name()); // .name() Returns the name of this enum constant, exactly as declared in its enum declaration
				
				// 3) Execute insert
				prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
	
				// 4) Retrieve the auto-generated PK from the DB 
				try (ResultSet rs = prep.getGeneratedKeys()) { // try-with-resources!!! (See ResultSet javadoc)
					// rs is a ResulSet (table) separate from our query parameters with 1 column containing the generated key (id)
					/* The content within () after the try clause is not a code block, it is the resource declaration.
					 * Any object we put there that implements AutoCloseable (like ResultSet) will be automatically closed at the end of the try block, even if an exception is thrown.
					 * If we want to remove this content in () and just put it within try{}, we must also explicitly call rs.close() to avoid leaking cursors or database resources.
					*/
		            if (rs.next()) {
		                c.setUserId(rs.getInt(1)); 
		            }
		            
		            // rs.close(); would be declared here if we don't use the resource declaration in the try clause
		        }
				// prep.close(); // Always close the PreparedStatement
				
				// 5) Commit once everything is done
	            manager.getConnection().commit(); // Commit everytime we do any change to the database
	
			} catch (Exception e) {
				e.printStackTrace(); // To print where the error comes from
			}
		} else {
			//TODO THROW A PERSONALISED EXCEPTION
		}
	}
	
	/**
	 * This method deletes the Client with the id passed by parameter.
	 * @param  id the unique identifier of the client to delete.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs
	 */
	@Override
	public void deleteClientbyID(Integer id) throws Exception { //TODO CREATE OUR INVALID ID EXCEPTION 
		String sql = "DELETE FROM client WHERE id=?";
		
		// 1) Prepare statement 
		try (PreparedStatement prep = manager.getConnection().prepareStatement(sql)){
			// 2) Bind parameters
			prep.setInt(1, id); // The 1 binds to the first and unique "?"

			// 3) Execute delete and throw an exception if no ID was found in the DB
			int rows = prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
	        if (rows == 0) {
	            throw new Exception("No client found with id " + id);
	            // Relaunch this exception because it is not the responsibility of this method to handle it
	        }
			
			//prep.close(); We don't need to do this since we have used a try-with resources
			
			// 4) Commit once everything is done
			manager.getConnection().commit(); // Commit everytime we do any change to the database
			
		} catch (SQLException e) { 
			// Catch this SQL exception because is the responsibility of this method to handle it 
			e.printStackTrace();
		}
	}
	
	/**
	 * This method retrieves all Client records (rows) from the database.
	 * @return a List of Client objects; never null but may be empty if there are no records.
	 */
	@Override
	public List<Client> getListOfClients() {
		List<Client> clients = new ArrayList<Client>();
		String sql = "SELECT * FROM client";
		
		try {
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);
			ResultSet rs = prep.executeQuery();

			while (rs.next()) {
				Integer id = rs.getInt("id");
				String name = rs.getString("name");
				String surname = rs.getString("surname");
				Integer phoneNumber = rs.getInt("phone_number");
				String email = rs.getString("email");
				String address = rs.getString("address");
				//Role role = Role.valueOf(rs.getString("role")); // valueOf() is a function from Enum, not a method.

				Client client = new Client(id, name, surname, phoneNumber, email, address);
				clients.add(client);
			}

			rs.close(); // Close the ResulSet manually if we don't use a try-with-resources
			prep.close(); // Close the PreparedStatement manually if we don't use a try-with-resources 

		} catch (Exception e) {
			e.printStackTrace();
		}
		return clients;
	}

	/**
	 * This method retrieves a single Client by its id.
	 * @param c_id the unique identifier of the client to retrieve.
	 * @return the matching Client object, or null if no such client exists.
	 *TODO: CORRECT THE RETURN SENTENCE ABOVE ^ (this method never returns a null, instead, throws an exception.
	 */
	@Override
	public Client getClientByID(Integer c_id) {
		Client client = null;

		try {
			Statement stmt = manager.getConnection().createStatement();
			String sql = "SELECT * FROM client WHERE id=" + c_id;
			ResultSet rs = stmt.executeQuery(sql);

			Integer id = rs.getInt("id");
			String name = rs.getString("name");
			String surname = rs.getString("surname");
			Integer phoneNumber = rs.getInt("phone_number");
			String email = rs.getString("email");
			String address = rs.getString("address");
			//Role role = Role.valueOf(rs.getString("role")); // valueOf() is a function from Enum, not a method.

			client = new Client(id, name, surname, phoneNumber, email, address);

			rs.close();
			stmt.close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return client;
	}

	/**
	 * This method looks up a Client by their unique email address.
	 * @param c_email the email address to search for.
	 * @return the matching Client object.
	 * @throws Exception if no client is found or if a database error occurs.
	 */
	@Override
	public Client getClientByEmail(String c_email) throws Exception {
		Client client = null;

		try {
			Statement stmt = manager.getConnection().createStatement();
			String sql = "SELECT * FROM client WHERE email = '" + c_email + "'";

			ResultSet rs = stmt.executeQuery(sql);
			Integer id = rs.getInt("id");
			String name = rs.getString("name");
			String surname = rs.getString("surname");
			Integer phoneNumber = rs.getInt("phone_number");
			String email = rs.getString("email");
			String address = rs.getString("address");
			//Role role = Role.valueOf(rs.getString("role")); // valueOf() is a function from Enum, not a method.

			client = new Client(id, name, surname, phoneNumber, email, address);

			rs.close();
			stmt.close();

		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return client;
	}
	
	@Override 
	/**
	 * Method that receives an email of a client and returns true if the client was already introduced in the database or false if not.
	 * @param c_email string that stores the email of the client whose presence in the database we want to check.
	 * @return true if the client is found in the database or false otherwise.
	 */
	public boolean isClientInDatabase(String c_email) {
		try {
			Statement stmt = manager.getConnection().createStatement();
			String sql = "SELECT * FROM client WHERE email = '" + c_email + "'";

			ResultSet rs = stmt.executeQuery(sql);
			if(rs.next()) {
				return true;
			}
			rs.close();
			stmt.close();

		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return false;
	}

	/**
	 * This method updates the name field of the Client with the given ID.
	 * @param id the unique identifier of the client to update.
	 * @param name the new name to assign.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs.
	 */
	@Override
	public void updateName(Integer id, String name) throws Exception {
		try {
			String sql = "UPDATE client SET name = ? WHERE id = ?";
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);

			prep.setString(1, name); // The 1 binds to the first "?"
			prep.setInt(2, id); // The 2 binds to the second "?"
			prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
			prep.close(); // Always close the PreparedStatement
			
			manager.getConnection().commit(); // Commit everytime we do any change to the database
		
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method updates the surname field of the Client with the given ID.
	 * @param id the unique identifier of the client to update.
	 * @param surname the new surname to assign.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs.
	 */
	@Override
	public void updateSurname(Integer id, String surname) throws Exception {
		try {
			String sql = "UPDATE client SET surname = ? WHERE id = ?";
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);

			prep.setString(1, surname); // The 1 binds to the first "?"
			prep.setInt(2, id); // The 2 binds to the second "?"
			prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
			prep.close(); // Always close the PreparedStatement
			
			manager.getConnection().commit(); // Commit everytime we do any change to the database
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method updates the phone number field of the Client with the given ID.
	 * @param id the unique identifier of the client to update.
	 * @param phoneNumber the new phone number to assign.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs.
	 */
	@Override
	public void updatePhoneNumber(Integer id, Integer phoneNumber) throws Exception {
		try {
			String sql = "UPDATE client SET phone_number = ? WHERE id = ?";
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);

			prep.setInt(1, phoneNumber); // The 1 binds to the first "?"
			prep.setInt(2, id); // The 2 binds to the second "?"
			prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
			prep.close(); // Always close the PreparedStatement
			
			manager.getConnection().commit(); // Commit everytime we do any change to the database
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method updates the address field of the Client with the given ID.
	 * @param id the unique identifier of the client to update.
	 * @param address the new address to assign.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs.
	 */
	@Override
	public void updateAddress(Integer id, String address) throws Exception {
		try {
			String sql = "UPDATE client SET address = ? WHERE id = ?";
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);

			prep.setString(1, address); // The 1 binds to the first "?"
			prep.setInt(2, id); // The 2 binds to the second "?"
			prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
			prep.close(); // Always close the PreparedStatement
			
			manager.getConnection().commit(); // Commit everytime we do any change to the database
		} catch (Exception e) {
			e.printStackTrace();
		}	
	}

	/**
	 * This method updates the email field of the Client with the given ID.
	 * @param id the unique identifier of the client to update.
	 * @param email the new email address to assign.
	 * @throws Exception if no client exists with the given ID, or if a database error occurs.
	 */
	@Override
	public void updateEmail(Integer id, String email) throws Exception {
		try {
			String sql = "UPDATE client SET email = ? WHERE id = ?";
			PreparedStatement prep = manager.getConnection().prepareStatement(sql);

			prep.setString(1, email); // The 1 binds to the first "?"
			prep.setInt(2, id); // The 2 binds to the second "?"
			prep.executeUpdate(); // Executes the SQL statement in this PreparedStatement object, which must be an SQL DML statement; or an SQL DDL statement (which returns nothing)
			prep.close(); // Always close the PreparedStatement
			
			manager.getConnection().commit(); // Commit everytime we do any change to the database
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
